In [4]:
#numpy的函数
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape((6,2))
print(a)
a+=2
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]


In [5]:
#numpy的索引/切片/修改
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape((6,2))
print(a[0,0])
print(a[0:3,0:2])
a[0:3,0:2] = 0
print(a)
a[0,0] = 1
print(a)
a[0:3,0:2] = np.array([[1,2],[3,4],[5,6]])
print(a)

1
[[1 2]
 [3 4]
 [5 6]]
[[ 0  0]
 [ 0  0]
 [ 0  0]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  0]
 [ 0  0]
 [ 0  0]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
